pipeline {
  agent any

  stages {
    stage('Build') {
      steps {
        sh 'docker build -t frontend .'
        sh 'docker tag frontend $DOCKER_FRONTEND_IMAGE'
      }
    }
    stage('Test') {
      steps {
      }
    }
    stage('Deploy') {
      steps {
        withCredentials([usernamePassword(credentialsId: "${DOCKER_REGISTRY_CREDS}", passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
          sh "echo \$DOCKER_PASSWORD | docker login -u \$DOCKER_USERNAME --password-stdin docker.io"
          sh 'docker push $DOCKER_FRONTEND_IMAGE'
        }
      }
    }
  }
  post {
    always {
      sh 'docker logout'
    }
  }
}