version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - api

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - api

  api:
    build: ./api
    ports:
      - "5001:5001"
